{{- if .Values.networkPolicy.enable }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "whoami-service.fullname" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "whoami-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Egress
    - Ingress
  ingress:
    - ports:
      - port: 8080
{{- end }}
