apiVersion: v1
kind: Service
metadata:
  name: {{ include "whoami-service.fullname" . }}
  labels:
    {{- include "whoami-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "whoami-service.selectorLabels" . | nindent 4 }}
